import "@/styles/global.css"

import type { Metadata } from "next"
import { Mulish } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"
import { SpeedInsights } from "@vercel/speed-insights/next"

import { ScrollArea } from "@/components/_ui/scroll-area"
import { SubscriptionProvider } from "@/context/SubscriptionContext"
import { SidebarProvider, SidebarTrigger } from "@/components/_ui/sidebar"

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["400", "600", "500", "700", "800"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "FinTrack AI",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY || ""}
      appearance={{
        baseTheme: dark
      }}
    >
      <html lang="en">
        <link rel="icon" href="/logo.svg" />
        <body className={`${mulish.className} dark antialiased`}>
          <SubscriptionProvider>
            <ScrollArea className="w-hull h-full">
              <SidebarProvider>
                <SidebarTrigger size={"default"} />
                {children}
                <SpeedInsights />
              </SidebarProvider>
            </ScrollArea>
          </SubscriptionProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
