import type { Metadata } from "next"
import { Mulish } from "next/font/google"

import "@/styles/global.css"
import {
  ClerkProvider,
} from "@clerk/nextjs"
import { dark } from "@clerk/themes"

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap"
})

export const metadata: Metadata = {
  title: "FinTrack AI",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark
      }}
    >
      <html lang="en">
        <body className={`${mulish.className} dark antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
